### ISSUE TITLE
QA_Point-Operations_References_Broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/image-processing-iiith#76] opened 2017-05-15 10:21 UTC
Defect Description :
In the References page of the Distance Point Operations experiment, the 4th link is navigating to error page.

Actual Result :
In the References page of the Distance Point Operations experiment, found broken link. The 4th link is navigating to error page.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
![qa_oe_ip_i20](https://cloud.githubusercontent.com/assets/13479177/26053401/5988c460-3986-11e7-8d2a-bc4ad6d5ac72.png)

**Comment by BSravanthi** [comment] 2017-05-15 10:23
Tried to find the link. Removed as could not get the relevant link.

**Comment by sravanthimodepu** [comment] 2017-07-01 09:27
Still the issue is not fixed and the link is existing in the references page. Hence reopening the issue.

**Comment by BSravanthi** [comment] 2017-07-03 04:51
Fixed

![qa_oe_ip_i52](https://user-images.githubusercontent.com/13479177/27778550-582caea0-5fd9-11e7-842c-75943b4b026f.png)

**Comment by BSravanthi** [comment] 2017-07-03 04:54
As the 3rd link is redirecting to an error page. removed the 3rd link too. 

![qa_oe_ip_i53](https://user-images.githubusercontent.com/13479177/27778602-c444537c-5fd9-11e7-8455-17e5ac99ba25.png)

**Comment by sravanthimodepu** [comment] 2017-07-04 05:12
Closing..

**Closed by sravanthimodepu** 2017-07-04 05:12 UTC
Labels: Category: Usability, Developed By: VLEAD, Open-edx-Issue, Resolved, Severity: S2
